'use client'

import DashboardLayout from '@/components/DashboardLayout'
import { FileText, Download } from 'lucide-react'
import { useState } from 'react'

export default function Reports() {
  const [selectedThreat, setSelectedThreat] = useState('')

  const handleGenerate = () => {
    if (!selectedThreat) return
    
    const reportContent = `
CYBERSHIELD AI THREAT INVESTIGATION REPORT
==========================================

Report Generated: ${new Date().toLocaleString()}
Threat ID: ${selectedThreat}

EXECUTIVE SUMMARY
-----------------
This report documents the investigation and analysis of a detected security threat.

THREAT CLASSIFICATION
--------------------
Type: Phishing
Risk Score: 87/100
Severity: High
Confidence: 89.2%

DETECTION EVIDENCE
-----------------
• Suspicious domain characteristics
• Multiple redirect patterns detected
• Unusual URL structure
• Missing security indicators
• ML model flagged as high-risk

FEATURE ANALYSIS
----------------
Domain Age: 12 days
URL Length: 87 characters
Redirects: 4
HTTPS: Enabled
Special Characters: 6

AI EXPLANATION
--------------
The URL was classified as high risk primarily because of its domain 
characteristics, redirect behavior, and unusual URL structure patterns 
detected by the machine learning model.

INVESTIGATION TIMELINE
---------------------
• Detected: ${new Date().toLocaleString()}
• Analyzed: ${new Date().toLocaleString()}
• Investigation Status: In Progress

RECOMMENDED ACTIONS
-------------------
1. Add indicator to watchlist for monitoring
2. Create incident for tracking
3. Block access at network level
4. Notify security team
5. Continue investigation

CURRENT STATUS
--------------
Investigation: In Progress
Last Updated: ${new Date().toLocaleString()}

---
Generated by CyberShield AI Security Platform
    `.trim()

    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `cybershield-report-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <DashboardLayout>
      <div className="max-w-4xl mx-auto space-y-6">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-primary/10 rounded-lg">
            <FileText className="w-8 h-8 text-primary" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-textPrimary">Threat Reports</h1>
            <p className="text-textSecondary">Generate comprehensive security reports</p>
          </div>
        </div>

        <div className="bg-card border border-border rounded-xl p-6">
          <h2 className="text-xl font-bold text-textPrimary mb-4">Generate Report</h2>
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-textPrimary mb-2">Select Threat</label>
              <input
                type="text"
                value={selectedThreat}
                onChange={(e) => setSelectedThreat(e.target.value)}
                placeholder="Enter Threat ID (e.g., THR-2026-00192)"
                className="w-full bg-secondary border border-border rounded-lg px-4 py-3 text-textPrimary placeholder-textSecondary focus:outline-none focus:border-primary"
              />
            </div>
            <button
              onClick={handleGenerate}
              disabled={!selectedThreat}
              className="w-full bg-primary hover:bg-primary/90 disabled:bg-primary/50 text-white font-semibold py-3 px-6 rounded-lg transition-all flex items-center justify-center gap-2"
            >
              <Download className="w-5 h-5" />
              Generate Report
            </button>
          </div>
        </div>

        <div className="bg-card border border-border rounded-xl p-6">
          <h2 className="text-xl font-bold text-textPrimary mb-4">Report Preview</h2>
          <div className="bg-secondary rounded-lg p-6 font-mono text-xs text-textPrimary space-y-3">
            <div className="text-sm font-bold border-b border-border pb-2">CYBERSHIELD AI THREAT INVESTIGATION REPORT</div>
            <div>
              <div className="text-textSecondary">Threat ID</div>
              <div>THR-2026-00192</div>
            </div>
            <div>
              <div className="text-textSecondary">Threat Type</div>
              <div className="text-danger">Phishing</div>
            </div>
            <div>
              <div className="text-textSecondary">Risk Score</div>
              <div>87/100 - HIGH RISK</div>
            </div>
            <div>
              <div className="text-textSecondary">Detection Evidence</div>
              <div>• Suspicious domain characteristics</div>
              <div>• Multiple redirect patterns</div>
              <div>• Unusual URL structure</div>
            </div>
            <div>
              <div className="text-textSecondary">AI Explanation</div>
              <div>The URL was classified as high risk primarily because of its domain characteristics and redirect behavior.</div>
            </div>
          </div>
        </div>
      </div>
    </DashboardLayout>
  )
}
